### ISSUE TITLE
Fix broken images when logged out

### ISSUE THREAD

**Issue by kayefox** [LogicalOutcomes/DHIS2-Curriculum#1]
Broken images found when logged out. But when logged in, they are not broken images.

[Fixing broken images (Web view) ](https://logicaloutcomes.sharepoint.com/sites/marketing/_layouts/OneNote.aspx?id=%2Fsites%2Fmarketing%2FSiteAssets%2FMarketing%20Notebook&wd=target%28DHIS2%2FCurriculum.one%7C644177C7-5D24-4E31-A047-6AF2E7207C02%2FFixing%20broken%20images%7C5E32C950-1697-6546-B54F-240F4B3D0139%2F%29)

**Comment by ChantriaTram** [comment]
Reply from GitHub help on our issue:

Hi Chantria,
It looks like those images are in private repositories, so they would only be visible to someone who is currently logged in as a user with access to the repositories. For example, the first broken image I see in the first URL you've sent is:
https://github.com/LogicalOutcomes/**TNC-DHIS2-training**/raw/I/MaintenanceApp.png?raw=true
I would suggest having them in the same public repository the wiki is in, instead.
______________________________
Looks like a lot of images are from the TNC-DHIS2-training repository for some reason. They should be coming from the Curriculum Repo instead, which is public. 

Stay tuned for what to do next...
