### ISSUE TITLE
Update videos with yellow bg

### ISSUE THREAD

**Issue by kayefox** [LogicalOutcomes/DHIS2-Curriculum#2]
List is here: [To update videos with yellow bg (Web view)](https://logicaloutcomes.sharepoint.com/sites/marketing/_layouts/OneNote.aspx?id=%2Fsites%2Fmarketing%2FSiteAssets%2FMarketing%20Notebook&wd=target%28DHIS2%2FCurriculum.one%7C644177C7-5D24-4E31-A047-6AF2E7207C02%2FTo%20update%20videos%20with%20yellow%20bg%7CA0B88418-A562-A149-AEEF-7D5388FD2AD8%2F%29)

**Comment by ChantriaTram** [comment]
I can't access this link...
