### ISSUE TITLE
Image in the page does not match with the video instructions

### ISSUE THREAD

**Issue by kayefox** [LogicalOutcomes/DHIS2-Curriculum#6]
[Create an Indicator Group](https://github.com/LogicalOutcomes/DHIS2-Curriculum/wiki/30.-Create-an-Indicator-Group) 
* It says to go to the ‘Maintenance’ App in the video but the instructions in Wiki says “Go to the 'Data Elements / Indicators' app”

**Comment by ChantriaTram** [comment]
done!
